#!/bin/sh 
#*******************************************************************
# r2clg
#	compile from refal to GNU-assembler + link + go
# 	arg: $1 - name of refal programm (without ext ref)
#	result: running of $1.exe 
#
# Copyright (C) Refal-2 Team
# Author: Leonid Belous (aka BLF)
# E-mail: belous@ilt.kharkov.ua
# Date: 28.05.2005
# *******************************************************************

bin/refal2 $1.ref > $1.log
as -o $1.o $1.asm >> $1.log
gcc -o $1.exe lib/r2objects/mainrf.o $1.o -Wl,-L./lib -Wl,-lrefal2,-lr2user >> $1.log
$1.exe
