#!/bin/sh
#*******************************************************************
# r2cl
#	compile from refal to GNU-assembler + assembling. 
# 	arg: $1 - name of refal programm (without ext ref)
#	result: $1.o add to user lib (libr2user.a) 
#
# Copyright (C) Refal-2 Team
# Author: Leonid Belous (aka BLF)
# E-mail: belous@ilt.kharkov.ua
# Date: 28.05.2005
#*******************************************************************

bin/refal2 $1.ref > $1.log
as -o $1.o $1.asm >> $1.log
ar -r lib/libr2user.a $1.o
