#!/bin/sh 
# *******************************************************************
# r2dclg
#	compile from refal to GNU-assembler + debugger link + go
# 	arg: $1 - name of refal programm (without ext ref)
#	result: running of $1.exe in debugging mode 
#
# Copyright (C) Refal-2 Team
# Author: Leonid Belous (aka BLF)
# E-mail: belous@ilt.kharkov.ua
# Date: 28.05.2005
# *******************************************************************

bin/refal2 $1 > $1.log
as -o $1.o $1.asm >> $1.log
gcc -o $1.exe lib/r2objects/rfdbg.o -Wl,-L./lib $1.o -Wl,-lrefal2,-lr2user >> $1.log
$1.exe
